#!/usr/bin/env python3
""" This script checks the outputs from a test run to see that the observable
behavior on the bus is the same for each log. That is, the emulators are
checked to see that the read and write the same values from the bus in the
same order.
"""

import sys
import glob

def readfile(dirname, emuname):
    """ returns the reported reads and writes in the file """
    for i in glob.glob("%s/%s.results" % (dirname, emuname)):
        with open(i, "r") as f:
            for line in f:
                fields = line.split(" ")
                if fields[0] in ('r', 'w'):
                    yield fields[:4]


def compare(dirname, a, b):
    alist = list(readfile(dirname, a))
    blist = list(readfile(dirname, b))

    if len(alist) != len(blist):
        print("%s and %s don't have the same number of bus accesses" % (a, b))
        sys.exit(1)

    for (num, (ab, bb)) in enumerate(zip(alist, blist)):
        if ab != bb:
            print("%s and %s disagree on bus access number %d" % (a, b, num))
            sys.exit(1)

compare(sys.argv[1], sys.argv[2], sys.argv[3])
