#!/usr/bin/env python3
""" This script checks the outputs from a test run to see that the internal
state of the CPU is the same for each log. That is, the emulators are checked
to see that the registers A, X and Y, the program counter, stack pointer and
status flags are the same, on each cycle. Therefore, this script also checks
that the number of bus accesses is the same.
"""

import sys
import glob

def readfile(dirname, emuname):
    """ returns the reported reads and writes in the file """
    for i in glob.glob("%s/%s.results" % (dirname, emuname)):
        with open(i, "r") as f:
            for line in f:
                fields = line.split(" ")
                yield fields[4:]


def compare(dirname, a, b):
    alist = list(readfile(dirname, a))
    blist = list(readfile(dirname, b))

    if len(alist) != len(blist):
        print("%s and %s don't have the same number of bus accesses" % (a, b))
        sys.exit(1)

    for (num, (ab, bb)) in enumerate(zip(alist, blist)):
        print(ab)
        print(bb)

        if ab != bb:
            print("%s and %s disagree on bus access number %d" % (a, b, num))
            sys.exit(1)

compare(sys.argv[1], sys.argv[2], sys.argv[3])
