#!/bin/bash

make
make -C rubbermallet
make -C gianlucag

EMUS="rubbermallet gianlucag mre_mos6502"

TESTCASE=$(cat "$1/input")

# run the test case on each emulator
for TESTER in $EMUS
do
	(cd $TESTER; ./test $TESTCASE > ../"$1"/$TESTER.results)
done
