#!/bin/bash

make

# Generate one random test case
TESTCASE="$(./generate_test_case)"

# Create a folder to store the test case and its results in
TESTDIR=tests/"$TESTCASE"
mkdir -p "$TESTDIR"

# Print the test case
echo $TESTCASE

# and store it.
echo $TESTCASE > "$TESTDIR"/input

./rerun "$TESTDIR"
